---
- name: show cam table
  hosts: all
  gather_facts: false
  connection: local

  tasks:
  - name: use ios_command module for showing cam table
    ios_command:
        commands:
            - show mac address-table
    register: print_output

  - debug: var=print_output.stdout_lines
