---
- name: show L3 addresses
  hosts: all
  gather_facts: false
  connection: local

  tasks:
  - name: use ios_command module for showing L3 addresses
    ios_command:
        commands:
            - show ip int br
    register: print_output

  - debug: var=print_output.stdout_lines
