---
- name: show interface counters
  hosts: all
  gather_facts: false
  connection: local

  tasks:
  - name: show interface counters using ios_command module
    ios_command:
        commands:
        - show interfaces | i CRC|errors|rate|protocol|runts|late
    register: print_output

  - debug: var=print_output.stdout_lines

