---
    - name: Show the neighbors
      hosts: all
      gather_facts: false

      tasks:
        - name: show cdp neighbors
          raw: "sh cdp nei"
          register: print_output

        - name: print the output
          debug: var=print_output.stdout_lines
