---
    - name: show the status of interfaces
      hosts: all
      gather_facts: false

      tasks:
        - name: show int status
          raw: "sh int status"
          register: print_output

        - name: print the output
          debug: var=print_output.stdout_lines
